# Calculate reactions due to point loads
from numpy import ndarray


def exec(n: int, point_loads: ndarray, A: int, B:int):      
    xp = point_loads[n,0] #Location of point load
    fx = point_loads[n,1] #Point load horizontal component magnitude 
    fy = point_loads[n,2] #Point load vertical component magnitude 
    
    la_p = A-xp  #Lever arm of point load about point A
    mp = fy*la_p #Moment generated by point load about A - closkwise moments are positive
    la_vb = B-A  #Lever arm of vertical reaction at B about point A
 
    Vb = mp/la_vb #Vertical reaction at B
    Va = -fy-Vb   #Vertical reaction at A
    Ha = -fx      #Horizontal reaction at A
    
    return Va, Vb, Ha